### ISSUE TITLE
commons-io in redpen-server/pom.xml

### ISSUE THREAD

**Issue by jmoriya** [redpen-cc/redpen#149]
Do we need to add commons-io in redpen-server/pom.xml?
mvn jetty:run in my new box works well after adding the follows:

```XML
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-io</artifactId>
  <version>1.3.2</version>
</dependency>
```

**Comment by takahi-i** [comment]
I will close this issue since there is no report on this problem from users.
