### ISSUE TITLE
Undesirable detected of InvalidExpression

### ISSUE THREAD

**Issue by kubosho** [redpen-cc/redpen#465]
> 著作権の目的となつている著作物（以下この款において単に「著作物」という。）は、個人的に又は家庭内その他これに準ずる限られた範囲内において使用すること（以下「私的使用」という。）を目的とするときは、次に掲げる場合を除き、その使用する者が複製することができる。

The above statement is written in the quote format of markdown.

This statement has been thrown InvalidExpression by RedPen.

I want to quote not change the sentence.

So I hope not throw InvalidExpression in quote format of markdown.

**Comment by takahi-i** [comment]
Thank you very much for the feedback @kubosho!

> So I hope not throw InvalidExpression in quote format of markdown.

I think your idea not to validate quote sentences since the quote sentences are not written by the document authors. I will look into the code and check if we can fix the behavior.

**Comment by kubosho** [comment]
:+1:

**Comment by takahi-i** [comment]
This issue was fixed with #495 @kubosho. I will close this issue. When the error is not fixed in your environment, please let me know.  I will reopen this issue.

**Comment by takahi-i** [comment]
This patch is going to be included in RePen v1.4.1.

**Comment by kubosho** [comment]
@takahi-i 
Sorry for late response, thanks for fixed error! I am looking forward to release v1.4.1.

**Comment by kubosho** [comment]
@takahi-i 
I confirmed not throw InvalidExpression in quote format @ v1.4.1

very very thanks!
