### ISSUE TITLE
Corrupted Japanese characters in Windows platform (CLI)

### ISSUE THREAD

**Issue by so-c** [redpen-cc/redpen#500]
#410 was closed but Japanese characters are still crrupted in Windows Platform (CLI).

The parameter (-Dfile.encoding=UTF-8) was not added to bin\redpen.bat. If The parameter is added, message corruption is fixed. [INFO] messages get currupted but it is acceptable for me.

**Comment by takahi-i** [comment]
Thanks @so-c, I will fix with the parameter, -Dfile.encoding=UTF-8.

**Comment by takahi-i** [comment]
Hi @so-c, I will close this issue since the #502 fixed the character corruption in Windows. Please let us know when the patch does not work for your environment. I will reopen this issue or create  another issue.

**Comment by so-c** [comment]
Thank you, it works well  for my environment, too.
