### ISSUE TITLE
RedPen build fail in the environments where LANG is not en

### ISSUE THREAD

**Issue by takahi-i** [redpen-cc/redpen#505]
I will look into the report below.

https://twitter.com/hak7a3/status/663207669587558400

**Comment by hak7a3** [comment]
I saw this failure on windows 10, jdk1.8.0u66, and marven 3.3.3:

Failed tests:   testFormatErrorsFromMarkdownParser(cc.redpen.formatter.JSONBySentenceFormatterTest): expected:<[Found invalid symbol "。".]> but was:<[不正なシンボル "。" がみつかりました。]>

**Comment by takahi-i** [comment]
Thank you very much for the report @hak7a3! I made a hotfix for this problem. Hopefull this patch  (#506) work for you.

**Comment by hak7a3** [comment]
Many thanks!! It works well.

**Comment by takahi-i** [comment]
Close with PR #506
