### ISSUE TITLE
false detection of Okurigana (競"合し"て)

### ISSUE THREAD

**Issue by kubosho** [redpen-cc/redpen#517]
- Infrastructure
    - RedPen version: 1.4.1
    - OS: OS X El Capitan 10.11.1
    - JDK: 1.8.0_65

---

I run this command with markdown file, then RedPen log a `Invalid Okurigana expression`.

```
redpen -c settings/redpen-conf-ja.xml -f markdown ./draft/ch05.md
```

log:

```
ch05.md:11: ValidationError[Okurigana], Found an invadid Okurigana expression "合し" at line: (function () { ... })(); を書かなかった場合、他のソースコードと競合してしまい、JavaScript が正常に動作しないことが起こります。
```

RedPen config file:

https://github.com/o2project/start-dash-of-site-making/blob/ee84d881d7b24c7029135f1e5da1e59773e1128a/settings/redpen-conf-ja.xml

target file:

https://github.com/o2project/start-dash-of-site-making/blame/d8e612f2412c75a11824880891bd1436e84607e3/draft/ch05.md#L11

**Comment by takahi-i** [comment]
Thank you a lot for the reports @kubosho! I will take the problem.

**Comment by takahi-i** [comment]
I added the fix in the previous commit. Hopefully the patch works for you.

**Comment by takahi-i** [comment]
I close this issue. Please let me know when the patch does not work in your environment. I will reopen this issue or create another one.

**Comment by kubosho** [comment]
:+1:
