### ISSUE TITLE
Character corruption in redpen-server on Windows10

### ISSUE THREAD

**Issue by kozo2** [redpen-cc/redpen#545]
Like this image

![redpen](https://cloud.githubusercontent.com/assets/12192/12836509/f495021e-cbfc-11e5-8499-685157242388.PNG)

I tried the following encoding in Google chrome 49.0.2623.28 beta-m (64-bit)
- UTF8
- Shift_JIS
- EUC-JP
- ISO-2022-JP
- ISO-8859-10

How to reproduce the image
---------------------------------------
- Windows10, Java SE 8u72
- download redpen release 1.4.3 and untar

```
cd redpen-distribution-1.4.3\bin
java -jar redpen-server.war
```

**Comment by takahi-i** [comment]
Thank you a lot for the report @kozo2!

**Comment by taky** [comment]
@kozo2: Please set the system property **file.encoding** to **UTF-8** in order to launch the server.  You can set it with the environment variable _JAVA_OPTIONS, for example:

    cd redpen-distribution-1.4.3\bin
    set _JAVA_OPTIONS="-Dfile.encoding=UTF-8"
    java -jar redpen-server.war

Hope this helps!

**Comment by takahi-i** [comment]
:+1:

**Comment by takahi-i** [comment]
We are also considering to provide a bat file with which users can run without setting the environment variable by themselves.

**Comment by takahi-i** [comment]
Nice!
