### ISSUE TITLE
Excluding floating point numbers in InvalidSymbolValidator?

### ISSUE THREAD

**Issue by keichi** [redpen-cc/redpen#613]
I have a configuration to mark `.` as an invalid character: `<symbol name="FULL_STOP" value="．" invalid_chars="。."/>`.

This works fine, but it throws an error if the sentence contains floating point numbers (e.g. `Ubuntu 14.04`). I think it's quite rare to write floating point numbers using zenkaku periods in Japanese, especially in technical/scientific contexts. Is it possible to exclude floating point numbers from the InvalidSymbolValidator?

**Comment by takahi-i** [comment]
Thanks  a lot for the valuable feedback @keichi! I will give it a try to add special handling for exclusion of floating point numbers .

**Comment by takahi-i** [comment]
Hello @keichi I made a quick fix of this problem in #613.  Hopefully this fix works for you.
