### ISSUE TITLE
Suppress validation errors with annotation for AsciiDoc

### ISSUE THREAD

**Issue by takahi-i** [redpen-cc/redpen#616]
https://gist.github.com/takahi-i/fb1b7a2ea0e052d7985cea1e0bc82309

**Comment by gerryhocks** [comment]
I've created a pull request that attempts to solve this by using a preprocessor. It seems to work properly for all parser dialects.

If you have time, please feel free to test the implementation. Don't hesitate to ask if you have any queries or suggestions.

**Comment by takahi-i** [comment]
Thank  you very much for the contribution @gerryhocks! I got the suggestion on annotation style of AsciiDoc. I think that the suggestion is reasonable and therefore I would like you to change the annotation format of AsciiDoc format.

**Comment by gerryhocks** [comment]
I saw the suggestion too - no problem at all :)

**Comment by gerryhocks** [comment]
I've updated the pull request to reflect this format. It is a little more flexible than the AsciiDoc format in that the quotes and case are not required. So,
```
[suppress="Spelling Contraction"]
```
and
```
[suppress=spelling contraction]
```

are equivalent.

By default this suppression is scoped to the section you are in. It is a little tricky to scope this to a single paragraph, though I can try to get this working if it is required.

However, you can explicitly turn suppression off in the following way:
```
[suppress=spelling contraction]
In this article, we'll call a computer server that works as 
a member of a cluster an _instance_. for example, as shown in this 
[suppress=none]
http://redpen.ignored.url/[mishpelled link], each instance in 
distributed search engines stores the the fractions of data.
```

**Comment by gerryhocks** [comment]
I need to update this so the suppression annotation can be detected inside the various comment formats for the other markup formats.

**Comment by takahi-i** [comment]
I this close this issue, since the changes for supporting annotation with AsciiDoc attribute style (#632)  was merged. Comment style of the annotation is implemented with another issue and pull request.
