### ISSUE TITLE
DuplicatedSection validator preserves the document across the http requests.

### ISSUE THREAD

**Issue by karronoli** [redpen-cc/redpen#621]
on RedPen 1.5.5, Does redpen-server preserve the document?
Each time I make an HTTP request, it increases the same log from redpen-server.

$ curl -s --data-urlencode document=Hello --data documentParser=PLAIN --data format=plain --data lang=en http://redpen.herokuapp.com/rest/document/validate/
$ curl -s --data-urlencode document=Hello --data documentParser=PLAIN --data format=plain --data lang=en http://redpen.herokuapp.com/rest/document/validate/
0: ValidationError[DuplicatedSection], Found duplicated section (starts from line 0). at line:
$ curl -s --data-urlencode document=Hello --data documentParser=PLAIN --data format=plain --data lang=en http://redpen.herokuapp.com/rest/document/validate/
0: ValidationError[DuplicatedSection], Found duplicated section (starts from line 0). at line:
0: ValidationError[DuplicatedSection], Found duplicated section (starts from line 0). at line:
$ curl -s --data-urlencode document=Hello --data documentParser=PLAIN --data format=plain --data lang=en http://redpen.herokuapp.com/rest/document/validate/
0: ValidationError[DuplicatedSection], Found duplicated section (starts from line 0). at line:
0: ValidationError[DuplicatedSection], Found duplicated section (starts from line 0). at line:
0: ValidationError[DuplicatedSection], Found duplicated section (starts from line 0). at line:

Are you sure?

**Comment by takahi-i** [comment]
Thank you very much for the valuable report @karronoli! I will look into the wired behavior.

**Comment by taky** [comment]
PR sent, please review.

**Comment by takahi-i** [comment]
Hi @karronoli, I made hot-fix of this issue and merge it. Hopefully this fix works for your environment.

**Comment by karronoli** [comment]
Thanks @takahi-i @taky ! I've built a5db967bea90fb758e3833df198fc4831f64b862 (#634) to check. The problem is fix!!

**Comment by takahi-i** [comment]
Thanks for the  contributions @karronoli @taky!
