### ISSUE TITLE
Mismatch Content-Type?

### ISSUE THREAD

**Issue by karronoli** [redpen-cc/redpen#624]
I make a request to redpen-server to return the response in xml format. the response body is correct.
But the Content-Type header is not correct. it is application/json.
Does redpen-server always returns application/json?
https://github.com/redpen-cc/redpen/blob/redpen-1.5.5/redpen-server/src/main/java/cc/redpen/server/api/RedPenResource.java#L91

$ curl --verbose --data-urlencode document="古池や,蛙飛び込む水の音" --data documentParser=PLAIN --data format=xml --data lang=ja http://redpen.herokuapp.com/rest/document/validate/  2>&1| grep '< Content-Type'
< Content-Type: application/json
$ curl --verbose --data-urlencode document="古池や,蛙飛び込む水の音" --data documentParser=PLAIN --data format=plain --data lang=ja http://redpen.herokuapp.com/rest/document/validate/  2>&1| grep '< Content-Type'
< Content-Type: application/json

**Comment by takahi-i** [comment]
Thank you very much for the valuable report @karronoli!  We will look into the behavior and fix it.

**Comment by taky** [comment]
I'll take care of the issue

**Comment by takahi-i** [comment]
👍

**Comment by karronoli** [comment]
:+1: :+1:

**Comment by takahi-i** [comment]
This issue is fixed with #635.  Thanks @karronoli and @taky!
