### ISSUE TITLE
Deviated row number of latex text

### ISSUE THREAD

**Issue by ABCanG** [redpen-cc/redpen#626]
Incorrect report is output when latex text containing comment is entered.
Line number is deviated by the number of comments.
Moving to the next section, it will be reset to the correct line number.
The following is the result of the [demo page](http://redpen.herokuapp.com/).

Input:
```latex
\section{first}
I like sushi.
% comment
I like noodles.
% comment
I like bread.

\section{second}
You like sushi too.
```

Output:
```
Line 2:2 “I 【like】 sushi.”
Found invalid word "like".

Line 3:2 “ I 【like】 noodles.”
Found invalid word "like".

Line 4:2 “ I 【like】 bread.”
Found invalid word "like".

Line 9:4 “You 【like】 sushi too.”
Found invalid word "like".
```

Should be:
```
Line 2:2 “I 【like】 sushi.”
Found invalid word "like".

Line 4:2 “ I 【like】 noodles.”
Found invalid word "like".

Line 6:2 “ I 【like】 bread.”
Found invalid word "like".

Line 9:4 “You 【like】 sushi too.”
Found invalid word "like".
```

**Comment by taky** [comment]
Thanks for your report @ABCanG!  I'll investigating the case.

**Comment by taky** [comment]
PR sent, please review.

**Comment by ABCanG** [comment]
I tried this pull request and confirmed that the correct report is output.
Thank you!

**Comment by takahi-i** [comment]
Thank you very much for checking the patch in your environment @ABCanG! I close this Issue since the Pull Request #630 was merged.
