### ISSUE TITLE
Labeled of asciidoc is not parsed.

### ISSUE THREAD

**Issue by kongou-ae** [redpen-cc/redpen#683]
The labeled of single-line is not parsed correctly. When I use labeled of multi-line, The label is not parsed.

# Labeled, single-line

## asciidoc

```
first term:: definition of first term

section term:: definition of second term
```

## Validator

```
function validateSentence(sentence) {
  console = {
      log:print
  };
  console.log(sentence.content)
}
```

## Result

```
first term1:: definition of first term1
section term1:: definition of second term1
```

# Labeled, multi-line

## asciidoc

```
first term::
definition of first term

section term::
definition of second term
```

## Validator

```
function validateSentence(sentence) {
  console = {
      log:print
  };
  console.log(sentence.content)
}
```

## Result

```
definition of first term
definition of second term
```

**Comment by takahi-i** [comment]
Thank you very much for the report @kongou-ae! I will look into this issue.

**Comment by takahi-i** [comment]
I fixed this issue in #685. Hopefully this fix works for you. I will close this issue but please let me know  if you still have the problem.

**Comment by kongou-ae** [comment]
Thanks. I tested this. But Labeled is not parsed. Specific examples are as follows.

```
hogehoge:: 
ほげほげー

hogehoge::
* ほげほげー
* ほげほげー
* ほげほげー
```

`ほげほげ` is parsed to ListElement. But  `hogehoge` is not parsed to ListElement.

**Comment by takahi-i** [comment]
I think the current RedPen coverers first example, however I have not seen the second example (labeled list containing standard list elements). If AsciiDoc supports the second, we will fix the parser to handle the following sample.

```
hogehoge::
* foo
* bar
* baz
```
