### ISSUE TITLE
KatakanaSpellCheck Not Working in V1.7

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#708]
Testing RedPen V1.5.5 and V1.7 on the same file. V1.5.5 picks up varying numbers of katakana word pairs depending on the min_ratio setting. V1.7 does not appear to find any, whatever the min_ratio setting.

**Comment by edwardwoodward** [comment]
I reinstalled RedPen V1.7 and got KatakanaSpellCheck to flag some word pairs, but it still doesn't seem to work as described. I have pairs such as 「マインド」 and 「バインド」, and 「アプリケーション」 and 「アロケーション」 which are not flagged even with min_ratio set to 0.9, yet pairs such as 「マインド」 and 「メソッド」, and 「スタック」 and 「メソッド」 are flagged at 0.7. (At 0.6 and below, nothing is flagged.) Incidentally, the example in your documentation ( 「インデクス」 and 「インデックス」) is not flagged at 0.9.

**Comment by takahi-i** [comment]
Thank you very much for the report @edwardwoodward! As you reported,  「マインド」 and 「バインド 」 should be detected.  I will look into the behavior and check if there is a space to improve the validator.

**Comment by edwardwoodward** [comment]
Thank you for the reply. I am currently testing RedPen to see how thoroughly it catches errors. I am quite happy to continue to point out issues in this way if you think it will be of assistance. I am no programmer, so I am afraid I cannot help with that side of RedPen, but I would be happy to help out with the documentation and testing.

**Comment by takahi-i** [comment]
Hello @edwardwoodward. Reporting on RedPen problems and feature request on any languages would be very helpful for us. 

> but I would be happy to help out with the documentation and testing.

Thank you so much for the offer! It would be very helpful if you check the English of RedPen manual. The following is the URL of RedPen manual. 

http://redpen.cc/docs/latest/index.html

And the source files are in the following repository.

https://github.com/redpen-cc/redpen-doc

**Comment by edwardwoodward** [comment]
I have finished checking the English documentation up to the last of the validators. I have used Word so that you can see what I have changed. I have used yellow highlight to denote either a question from me or a description that I have not been able to check.
I recommend that someone at your end checks what I have changed before changing the HTML file.
I am happy to continue checking the rest of the documentation (from "RedPen Configuration") if it will be of use.
[RedPen1.docx](https://github.com/redpen-cc/redpen/files/543491/RedPen1.docx)

**Comment by takahi-i** [comment]
Thanks but I am not able to see the docx file.. I will close this issue. Would be very  helpful to  add the issue  in the [redpen-doc](https://github.com/redpen-cc/redpen-doc) repository for the mistakes of documents.
