### ISSUE TITLE
DuplicatedSection not Working

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#709]
Testing RedPen V1.5.5 and V1.7 on the same file (Japanese text). I cannot get DuplicatedSection to work at all, even if I copy and paste a section in different places in the document (exactly the same section or with just one word changed). Is there a minimum section length?

**Comment by takahi-i** [comment]
Thank you very much for the report @edwardwoodward! I will look into the behavior.

**Comment by takahi-i** [comment]
Hello, in my environment, Duplicated section works for the following toy sample. Could you please give us the sample and the configuration (if you change the properties)? 


```
これはテスト
------------

これはテスト用のサンプルです。

これもテスト
------------
```

**Comment by edwardwoodward** [comment]
My apologies - I have only just noticed your comment. In my environment, DuplicatedSection does not work for your sample. I'm using Japanese Windows 8.1.
I tried by adding your sample to my sample file and also by creating a text file consisting only of your sample.
I tried by using my test config file and also by using a config file with DuplicatedSection as the only validator.
I also tried by using DuplicatedSection and DoubledWord as the only validators. In this case, DoubledWord flags "これ" and "テスト", so RedPen is reading the file.

**Comment by edwardwoodward** [comment]
Sorry, wrong button!

**Comment by takahi-i** [comment]
hmmm.. interesting. could you please tell me the command  with the options you run?

**Comment by edwardwoodward** [comment]
For Japanese files, I use:
redpen -r plain2 -c ../conf/redpen-conf-ja.xml D:\RedPen\Provider\target-j.txt > output-j.txt

**Comment by takahi-i** [comment]
DuplicateSection does not work for plain text. DuplicateSection only works for markup formats such as Markdown or AsciiDoc.
