### ISSUE TITLE
SectionLength behaviour and message in Japanese

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#712]
2 points:
1. How does SectionLength delimit sections? It treats each text file I have tried it with as a single section.
2. The phrasing of the Japanese flag message is odd. For example, it says:
SectionLength: セクション内の文字数が最大の"5,235"を超えています

5,235 is the number of characters in the file, not the number specified in max_num in the validator.

**Comment by edwardwoodward** [comment]
The same 2 points apply to ParagraphNumber:
1. How does ParagraphNumber delimit paragraphs?
2. The phrasing of the Japanese flag message is odd. For example, it says:
ParagraphNumber: セクション内のパラグラフ数が最大の"21"を超えています

21 is the number of paragraphs in the section (as determined by RedPen), not the number specified in max_num in the validator.

**Comment by takahi-i** [comment]
Could you please add another issue for the paragraph number thing? One issue should have only one topic. Otherwise we are not able to trace the status of the problem.

**Comment by edwardwoodward** [comment]
Will do.
Thank you for the replies so far.

**Comment by takahi-i** [comment]
> 1. How does SectionLength delimit sections? It treats each text file I have tried it with as a single section.

If plain text file format only have one section. if you need multiple sections, please write your document with markup text such as AsciiDoc or Markdown format.
