### ISSUE TITLE
Misleading Validator Names

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#713]
The following validator names are misleading and it might be better to rename them at a convenient time. I've added a suggestion for a new name and a reason why I think they are misleading.
1. VoidSection →　EmptySection
   "VoidSection" is confusing and doesn't really indicate a section with no content.
2. GappedSection →　MissingSection
   "GappedSection" indicates a section with gaps, but the point of the validator is to indicate that a section that should exist does not exist.
3. SpaceBetweenAlphabeticalWord →　SpaceBeforeAlphabeticalWord
   When I first tested this validator, I expected it to point out words that did not have a space before and after them. In fact it only points out words that do not have a space before them.

I'd also recommend dropping "Validator" from "StartWithCapitalLetterValidator" and "SpaceBeginningOfSentenceValidator", just because it seems odd that only they have it.

**Comment by takahi-i** [comment]
Thank you very much @edwardwoodward for the valuable comment!

**Comment by edwardwoodward** [comment]
It seems that you have already changed "SpaceBeginningOfSentenceValidator" to "SpaceBeginningOfSentence". The Japanese documentation lists "SpaceBeginningOfSentence" and the program does not recognise "SpaceBeginningOfSentenceValidator" → "There is no such validator".
I am rewriting the English documentation, so I will include this change.
It also seems that you have already changed "StartWithCapitalLetterValidator" to "StartWithCapitalLetter" but have not updated either the Japanese or English documentation.
I will add a separate issue about "SpaceBeginningOfSentence", because it does not seem to work.

**Comment by edwardwoodward** [comment]
Re: "SpaceBeginningOfSentence"
According to the Japanese documentation, this checks for a single-byte space between 2 sentences.
According to the English documentation, it checks for a space at the end of a sentence (presumably after the period) unless it's the end of the paragraph.
The Japanese description is easier to understand, so I'll change the English to match that. It would also make more sense to change the name to "SpaceBetweenSentences".
