### ISSUE TITLE
ParagraphNumber behaviour and message in Japanese

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#716]
1. How does ParagraphNumber delimit paragraphs?
2. The phrasing of the Japanese flag message is odd. For example, it says:
ParagraphNumber: セクション内のパラグラフ数が最大の"21"を超えています

21 is the number of paragraphs in the section (as determined by RedPen), not the number specified in max_num in the validator.

**Comment by takahi-i** [comment]
Thanks a lot @edwardwoodward!
