### ISSUE TITLE
SpaceBeginningOfSentence does not work

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#719]
Testing SpaceBeginningOfSentence on an English text file.
If there is no space between any two sentences, SpaceBeginningOfSentence is not flagged. Redpen appears to treat them as a single sentence and, if their combined length exceeds the set value, flags SentenceLength.

**Comment by takahi-i** [comment]
Hello @edwardwoodward. Thank you for the report! It looks like a bug. I will look into the behavior.

**Comment by takahi-i** [comment]
Make this validator deprecated in https://github.com/redpen-cc/redpen/pull/748 until we find a good solution.
