### ISSUE TITLE
Does SectionLength count words or characters?

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#724]
The Japanese and English manual descriptions of SectionLength say that it checks the number of words in a section, but the error message states "文字数" rather than "単語数". Which is correct?

Also, maybe because my machine is running Japanese Windows, I get most error messages in Japanese even using an English config file. Is there a way to show English messages for English files, Japanese messages for Japanese files? Alternatively, is there a list of messages somewhere?

**Comment by takahi-i** [comment]
From the source file, the length is based on character number.

**Comment by takahi-i** [comment]
Fixed in redpen-doc-ja
