### ISSUE TITLE
Strange behaviour of DoubleNegative

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#727]
This may not be important, but it struck me as odd. In an English text file, DoubleNegative flags a sentence that contains a negative ("no", "not" etc.) and "little". It is also odd that "negative + little" is flagged, but "negative + small" is not.

**Comment by takahi-i** [comment]
In my understanding, "little" is used as negative in english, but "small" is not negative use.

**Comment by edwardwoodward** [comment]
I think I see why you did this now. "Little" as in "There is little chance of success", which would equate to 少ない in Japanese, hence a negative meaning.
Personally, I think "little" and "small" are more often than not used interchangeably for 小さい, so I would drop it from the DoubleNegative list, but as I said originally, it is odd rather than important. I'll leave it with you.

**Comment by takahi-i** [comment]
Agree that "little" has non negative meaning, but the RedPen validator is not able to decide that "little" is negative or not in a sentence automatically.

If you want to get the errors with "little", please use suppress annotation (see http://redpen.cc/docs/latest/index.html#suppress-section), though the suppression works for AsciiDoc, LaTeX and Markdown.
