### ISSUE TITLE
EndOfSentence not described in Japanese documentation

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#730]
EndOfSentence is described in the English documentation, but not in the Japanese.
Is this only checking for periods etc inside and outside of quotation marks? I think the description needs fleshing out (more detail), but I don't have time to test it by trial and error.

**Comment by takahi-i** [comment]
Can you please add the issue in the RedPen Japanese document repository?

https://github.com/continuous-manual-writing/redpen-doc-ja

If you have a time, that would be helpful if you send the pull request.

**Comment by takahi-i** [comment]
Fixed in RedPen doc
