### ISSUE TITLE
HanakakuKana flags single-byte spaces and dashes

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#731]
HanakakuKana flags single-byte spaces and dashes as half-width kana. It may also be necessary to check if it flags other characters or symbols.

**Comment by takahi-i** [comment]
👍

**Comment by takahi-i** [comment]
Thank you very much for the valuable report I made the fix. Hopefully this patch works for you.

**Comment by edwardwoodward** [comment]
Is this patch in 1.7.6? I downloaded it, but it still flags single-byte spaces and dashes as half-width kana.
