### ISSUE TITLE
SuccessiveSentence: How should it work?

### ISSUE THREAD

**Issue by edwardwoodward** [redpen-cc/redpen#733]
The Japanese documentation states that SuccessiveSentence flags identical sentences in succession.
The English documentation states that it flags almost identical sentences in succession.
In practice, it flags almost identical sentences in succession.
1. Which is correct?
2. If "almost identical", how does RedPen decide?
3. If "almost identical", can the user change the degree of similarity? (e.g. by a property setting)

**Comment by takahi-i** [comment]
Hello, SuccessiveSentence apply the Edit Distance measure, I added the description on the parameters of this validator in the [RedPen manual](https://github.com/redpen-cc/redpen-doc/pull/79/commits/08bd2ec57b3833ad4e26044914c55f0caf4facf6).
