### ISSUE TITLE
Rename VoidSection

### ISSUE THREAD

**Issue by takahi-i** [redpen-cc/redpen#747]
VoidSection is not a good name for users to understand the role. I will rename this validator to ``SectionWIthoutIntroduction``.

**Comment by edwardwoodward** [comment]
Hello,
According to the documentation, 
"This validator generates errors if sections in input documents do not have any paragraphs or sentences."
So "SectionWIthoutIntroduction" still seems misleading - it suggests there may be other content besides the introduction. I think "EmptySection" would be a better name. (Unless the manual description is incomplete - perhaps it allows for sections within sections.)

**Comment by takahi-i** [comment]
👍

**Comment by takahi-i** [comment]
Fixed with  #751
