### ISSUE TITLE
Offset error with Spelling and backtick before it

### ISSUE THREAD

**Issue by blueyed** [redpen-cc/redpen#754]
Given `foo.txt`:
```
I `Dockerfile`
```

`redpen -r json foo.txt` produces:

> [{"document":"foo.txt","errors":[{"sentence":"I `Dockerfile`","endPosition":{"offset":14,"lineNum":1},"validator":"Spelling","lineNum":1,"sentenceStartColumnNum":0,"message":"Found possibly misspelled word \"`Dockerfile`\".","startPosition":{"offset":2,"lineNum":1}}]}]

The `offset` with `startPosition` is 2 here, but should be 3.

It seems like the backtick caused the offset error here.

Also the offset for `endPosition` seems to be off.

**Comment by takahi-i** [comment]
I will take this issue.

**Comment by takahi-i** [comment]
I fixed the problem. Please let us know when you still have the problem in the origin/master branch.

**Comment by blueyed** [comment]
Thank you!
