### ISSUE TITLE
Dictionary of KatakanaSpellCheck

### ISSUE THREAD

**Issue by Y-Yasumoto** [redpen-cc/redpen#791]
I don't understand how to use dictionary of KatakanaSpellCheck.
Please teach me how to make dictionary of KatakanaSpellCheck.

**Comment by takahi-i** [comment]
Hi @Y-Yasumoto, 

Thank you very much for using RedPen. The dictionary format of the KatakanaSpellCheck is the same as [SuggestExpression](http://redpen.cc/docs/latest/index.html#suggestexpression). 

If you need more details, please tell us on gitter channel. We provides the [English](https://gitter.im/redpen-cc/redpen/redpen) and [Japanese](https://gitter.im/redpen-cc/redpen/redpen-ja) channel.
