### ISSUE TITLE
JoyoKanji skips some words

### ISSUE THREAD

**Issue by teaplanet** [redpen-cc/redpen#804]
Person names appear in sentences but are not included in JoyoKanji.

I want to write like this.

```xml
<validator name="JapaneseJoyoKanji">
    <property name="list" value="圭,昌"/>
</validator>
```

**Comment by takahi-i** [comment]
@teaplanet Thank you for adding reasonable issue! I close this issue since I merged your pull request on the fix of this issue. 

Thank again and looking forward to further contribution!
