### ISSUE TITLE
Enable black-listing (disabling) validators

### ISSUE THREAD

**Issue by NicolasWebDev** [redpen-cc/redpen#815]
From what I have understood from the documentation, so far it is only possible to enable a list of validators (white-listing) or all of them.

I think it would be nice to have a way to disable specific validators, for example, if I want all of them enabled but for Hyphenation.

**Comment by takahi-i** [comment]
Hello @NicolasWebDev, 

Thank you very much for the interest in RedPen!

RedPen command (`redpen`) applies validators in default setting file.  The following is the default setting file.
 
https://github.com/redpen-cc/redpen/blob/master/redpen-cli/sample/conf/redpen-conf-en.xml

We can specify the setting file  which fits your writing standard  to `redpen` command. 

For example, when you save the following setting naming `my-redpen-conf.xml` which only have `SentenceLength` Validator.

```
<redpen-conf lang="en">
    <validators>
        <validator name="SentenceLength">
            <property name="max_len" value="120"/>
        </validator>
</redpen-conf>
```
And then run `redpen` command with `-c` option.  For example  the following command just check the length of the input sentences.

```
repden -c my-redpen-conf.xml input.md
```

For more details, please see http://redpen.cc/docs/latest/index.html#configuration-file.

**Comment by takahi-i** [comment]
I close this issue. Please reopen when you have further questions @NicolasWebDev.
