### ISSUE TITLE
errors (<<< ERRORs) throughout the ui.RedPenDemoTest

### ISSUE THREAD

**Issue by WaterSibilantFalling** [redpen-cc/redpen#868]
I have the Debian packages phantomjs, python3-selenium and python-selenium installed. 

I can't find any Debian package containing 'ghostdriver' .  Is the fundamental error 'ghostdriver'? 

EDIT: on this page https://github.com/codeborne/ghostdriver which is the current 'ghostdriver' implementation, it says:

> ### Setup
> 
> Download latest stable PhantomJS from here
> Selenium version ">= 3.3.1"
> 
> THAT'S IT!! Because of latest stable GhostDriver being embedded in PhantomJS, you shouldn't need anything else to get started.
> 

There is no 'ghostdriver' file in redpen itself. 

Thanks for any pointers or help

\-------------------------------------------------------------------------------
Test set: ui.RedPenDemoTest
\-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 4.559 sec <<< FAILURE! - in ui.RedPenDemoTest
redpenEditorIsPrepopulated()  Time elapsed: 1.222 sec  <<< ERROR!
org.openqa.selenium.UnsupportedCommandException: 
Error - Unable to load Atom 'execute_script' from file ':/ghostdriver/./third_party/webdriver-atoms/execute_script.js'
Command duration or timeout: 225 milliseconds
Build info: version: '2.49.0', revision: '365eeb44deba2067b1761c8862ef21d55250e063', time: '2016-01-13 11:57:39'
System info: host: 'Isis', ip: '192.168.1.77', os.name: 'Linux', os.arch: 'amd64', os.version: '4.19.0-4-amd64', java.version: '11.0.4'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.1.1, platform=LINUX, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.2.0, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: c1906660-0b40-11ea-bb9b-3131c0fb42c1
	at ui.RedPenDemoTest.loadRedPen(RedPenDemoTest.java:84)

**Comment by takahi-i** [comment]
Thanks! Removed DRedPenDemoTest since PhantomJS is deprecated..
