### ISSUE TITLE
Question or Feature Request: redpen output plain with filepath for filename

### ISSUE THREAD

**Issue by tsuyoshicho** [redpen-cc/redpen#869]
## log:
see this log
https://github.com/tsuyoshicho/action-redpen/pull/2/checks?check_run_id=368988899

[![Screenshot from Gyazo](https://gyazo.com/db412b614357c4e239ce8399b3d8025a/raw)](https://gyazo.com/db412b614357c4e239ce8399b3d8025a)

This log is working with reviewdog.

File-link is dead.

## reason:

redpen report plain
```
<file without path>:<line>:<message>
```

This format like Vim [errorformat](https://github.com/reviewdog/errorformat) (e.g. grep,...)

But unavailable due to missing information and incomplete file name. lost path.

## request:
I want to output with files path as an option or default.

Or if already have that feature, please let me know

**Comment by tsuyoshicho** [comment]
example filepath alive log
tool: textlint

https://github.com/tsuyoshicho/action-textlint/pull/2/checks?check_run_id=349166176

**Comment by takahi-i** [comment]
Thank you very much for the feature request. I will look into this issue and hopefully add some fix for the problem.  In my understanding, the problem come from redpen plain format does not contains the file path.

**Comment by tsuyoshicho** [comment]
Yes, It is.

**Comment by takahi-i** [comment]
I see. I will gives it a try 👍

**Comment by takahi-i** [comment]
I released version 1.10.4 https://github.com/redpen-cc/redpen/releases/tag/redpen-1.10.4 contains this patch. I close this issue. Please let us know when you still have the problem reopening this issue @tsuyoshicho.

**Comment by tsuyoshicho** [comment]
OK, but 1.10.4 attached file is not 1.10.4? re-check, please.

**Comment by takahi-i** [comment]
oops ... I changed the name of the package.

**Comment by tsuyoshicho** [comment]
Thanks quickly!!
