### ISSUE TITLE
release artifact question

### ISSUE THREAD

**Issue by chenrui333** [redpen-cc/redpen#876]
I am trying to bump the formula version to the latest, `v1.10.4`, and we did notice there is artifact change.

```
-   url "https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.3/redpen-1.10.3.tar.gz"
+   url "https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.4/redpen-distribution-1.10.4-assembled.tar.gz"
```

Can you educate the difference? Thanks.

Relates to https://github.com/Homebrew/homebrew-core/pull/52961

**Comment by chenrui333** [comment]
Bump this issue.

**Comment by takahi-i** [comment]
Deeply sorry for the late response @chenrui333. I updated the artifact name.

**Comment by chenrui333** [comment]
Thanks a lot, just curious if that is desired :)

**Comment by chenrui333** [comment]
Closing the issue now.
